project_id = "rfeljyjaebgoehnlxxxk"

[functions.create-restaurant]
verify_jwt = false

[functions.import-menu]
verify_jwt = false

[functions.process-automations]
verify_jwt = false

[functions.create-mp-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false
