/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as KdsRouteImport } from './routes/kds'
import { Route as MenuAdminRouteImport } from './routes/menu-admin'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as AdminMizuIndexRouteImport } from './routes/admin-mizu/index'
import { Route as AdminMizuAssinaturasRouteImport } from './routes/admin-mizu/assinaturas'
import { Route as AdminMizuConfiguracoesRouteImport } from './routes/admin-mizu/configuracoes'
import { Route as AdminMizuCuponsRouteImport } from './routes/admin-mizu/cupons'
import { Route as AdminMizuLogsRouteImport } from './routes/admin-mizu/logs'
import { Route as AdminMizuObservacoesExcluidasRouteImport } from './routes/admin-mizu/observacoes-excluidas'
import { Route as AdminMizuPagamentosRouteImport } from './routes/admin-mizu/pagamentos'
import { Route as AdminMizuPlanosRouteImport } from './routes/admin-mizu/planos'
import { Route as AdminMizuSuporteRouteImport } from './routes/admin-mizu/suporte'
import { Route as AdminMizuUsuariosRouteImport } from './routes/admin-mizu/usuarios'
import { Route as DevSheetHarnessRouteImport } from './routes/dev/sheet-harness'
import { Route as ExpedienteIndexRouteImport } from './routes/expediente/index'
import { Route as ExpedienteHistoricoRouteImport } from './routes/expediente/historico'
import { Route as MSlugRouteImport } from './routes/m/$slug'
import { Route as PedidoTokenRouteImport } from './routes/pedido/$token'
import { Route as QCodeRouteImport } from './routes/q/$code'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as ResetPasswordSuccessRouteImport } from './routes/reset-password/success'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as AdminMizuNotificacoesIndexRouteImport } from './routes/admin-mizu/notificacoes/index'
import { Route as AdminMizuNotificacoesAtualizacoesRouteImport } from './routes/admin-mizu/notificacoes/atualizacoes'
import { Route as AdminMizuRestaurantesIndexRouteImport } from './routes/admin-mizu/restaurantes/index'
import { Route as AdminMizuRestaurantesIdRouteImport } from './routes/admin-mizu/restaurantes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsRoute = KdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuAdminRoute = MenuAdminRouteImport.update({
  id: '/menu-admin',
  path: '/menu-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuIndexRoute = AdminMizuIndexRouteImport.update({
  id: '/admin-mizu/',
  path: '/admin-mizu/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuAssinaturasRoute = AdminMizuAssinaturasRouteImport.update({
  id: '/admin-mizu/assinaturas',
  path: '/admin-mizu/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuConfiguracoesRoute = AdminMizuConfiguracoesRouteImport.update({
  id: '/admin-mizu/configuracoes',
  path: '/admin-mizu/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuCuponsRoute = AdminMizuCuponsRouteImport.update({
  id: '/admin-mizu/cupons',
  path: '/admin-mizu/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuLogsRoute = AdminMizuLogsRouteImport.update({
  id: '/admin-mizu/logs',
  path: '/admin-mizu/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuObservacoesExcluidasRoute =
  AdminMizuObservacoesExcluidasRouteImport.update({
    id: '/admin-mizu/observacoes-excluidas',
    path: '/admin-mizu/observacoes-excluidas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMizuPagamentosRoute = AdminMizuPagamentosRouteImport.update({
  id: '/admin-mizu/pagamentos',
  path: '/admin-mizu/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuPlanosRoute = AdminMizuPlanosRouteImport.update({
  id: '/admin-mizu/planos',
  path: '/admin-mizu/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuSuporteRoute = AdminMizuSuporteRouteImport.update({
  id: '/admin-mizu/suporte',
  path: '/admin-mizu/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuUsuariosRoute = AdminMizuUsuariosRouteImport.update({
  id: '/admin-mizu/usuarios',
  path: '/admin-mizu/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSheetHarnessRoute = DevSheetHarnessRouteImport.update({
  id: '/dev/sheet-harness',
  path: '/dev/sheet-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedienteIndexRoute = ExpedienteIndexRouteImport.update({
  id: '/expediente/',
  path: '/expediente/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedienteHistoricoRoute = ExpedienteHistoricoRouteImport.update({
  id: '/expediente/historico',
  path: '/expediente/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordSuccessRoute = ResetPasswordSuccessRouteImport.update({
  id: '/reset-password/success',
  path: '/reset-password/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMizuNotificacoesIndexRoute =
  AdminMizuNotificacoesIndexRouteImport.update({
    id: '/admin-mizu/notificacoes/',
    path: '/admin-mizu/notificacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMizuNotificacoesAtualizacoesRoute =
  AdminMizuNotificacoesAtualizacoesRouteImport.update({
    id: '/admin-mizu/notificacoes/atualizacoes',
    path: '/admin-mizu/notificacoes/atualizacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMizuRestaurantesIndexRoute =
  AdminMizuRestaurantesIndexRouteImport.update({
    id: '/admin-mizu/restaurantes/',
    path: '/admin-mizu/restaurantes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMizuRestaurantesIdRoute = AdminMizuRestaurantesIdRouteImport.update({
  id: '/admin-mizu/restaurantes/$id',
  path: '/admin-mizu/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/kds': typeof KdsRoute
  '/menu-admin': typeof MenuAdminRoute
  '/orders': typeof OrdersRoute
  '/perfil': typeof PerfilRoute
  '/tables': typeof TablesRoute
  '/admin-mizu/assinaturas': typeof AdminMizuAssinaturasRoute
  '/admin-mizu/configuracoes': typeof AdminMizuConfiguracoesRoute
  '/admin-mizu/cupons': typeof AdminMizuCuponsRoute
  '/admin-mizu/logs': typeof AdminMizuLogsRoute
  '/admin-mizu/observacoes-excluidas': typeof AdminMizuObservacoesExcluidasRoute
  '/admin-mizu/pagamentos': typeof AdminMizuPagamentosRoute
  '/admin-mizu/planos': typeof AdminMizuPlanosRoute
  '/admin-mizu/suporte': typeof AdminMizuSuporteRoute
  '/admin-mizu/usuarios': typeof AdminMizuUsuariosRoute
  '/dev/sheet-harness': typeof DevSheetHarnessRoute
  '/expediente/historico': typeof ExpedienteHistoricoRoute
  '/m/$slug': typeof MSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/q/$code': typeof QCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/reset-password/success': typeof ResetPasswordSuccessRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/admin-mizu/': typeof AdminMizuIndexRoute
  '/expediente/': typeof ExpedienteIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin-mizu/notificacoes/atualizacoes': typeof AdminMizuNotificacoesAtualizacoesRoute
  '/admin-mizu/restaurantes/$id': typeof AdminMizuRestaurantesIdRoute
  '/admin-mizu/notificacoes/': typeof AdminMizuNotificacoesIndexRoute
  '/admin-mizu/restaurantes/': typeof AdminMizuRestaurantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/kds': typeof KdsRoute
  '/menu-admin': typeof MenuAdminRoute
  '/orders': typeof OrdersRoute
  '/perfil': typeof PerfilRoute
  '/tables': typeof TablesRoute
  '/admin-mizu/assinaturas': typeof AdminMizuAssinaturasRoute
  '/admin-mizu/configuracoes': typeof AdminMizuConfiguracoesRoute
  '/admin-mizu/cupons': typeof AdminMizuCuponsRoute
  '/admin-mizu/logs': typeof AdminMizuLogsRoute
  '/admin-mizu/observacoes-excluidas': typeof AdminMizuObservacoesExcluidasRoute
  '/admin-mizu/pagamentos': typeof AdminMizuPagamentosRoute
  '/admin-mizu/planos': typeof AdminMizuPlanosRoute
  '/admin-mizu/suporte': typeof AdminMizuSuporteRoute
  '/admin-mizu/usuarios': typeof AdminMizuUsuariosRoute
  '/dev/sheet-harness': typeof DevSheetHarnessRoute
  '/expediente/historico': typeof ExpedienteHistoricoRoute
  '/m/$slug': typeof MSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/q/$code': typeof QCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/reset-password/success': typeof ResetPasswordSuccessRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/admin-mizu': typeof AdminMizuIndexRoute
  '/expediente': typeof ExpedienteIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin-mizu/notificacoes/atualizacoes': typeof AdminMizuNotificacoesAtualizacoesRoute
  '/admin-mizu/restaurantes/$id': typeof AdminMizuRestaurantesIdRoute
  '/admin-mizu/notificacoes': typeof AdminMizuNotificacoesIndexRoute
  '/admin-mizu/restaurantes': typeof AdminMizuRestaurantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/kds': typeof KdsRoute
  '/menu-admin': typeof MenuAdminRoute
  '/orders': typeof OrdersRoute
  '/perfil': typeof PerfilRoute
  '/tables': typeof TablesRoute
  '/admin-mizu/assinaturas': typeof AdminMizuAssinaturasRoute
  '/admin-mizu/configuracoes': typeof AdminMizuConfiguracoesRoute
  '/admin-mizu/cupons': typeof AdminMizuCuponsRoute
  '/admin-mizu/logs': typeof AdminMizuLogsRoute
  '/admin-mizu/observacoes-excluidas': typeof AdminMizuObservacoesExcluidasRoute
  '/admin-mizu/pagamentos': typeof AdminMizuPagamentosRoute
  '/admin-mizu/planos': typeof AdminMizuPlanosRoute
  '/admin-mizu/suporte': typeof AdminMizuSuporteRoute
  '/admin-mizu/usuarios': typeof AdminMizuUsuariosRoute
  '/dev/sheet-harness': typeof DevSheetHarnessRoute
  '/expediente/historico': typeof ExpedienteHistoricoRoute
  '/m/$slug': typeof MSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/q/$code': typeof QCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/reset-password/success': typeof ResetPasswordSuccessRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/admin-mizu/': typeof AdminMizuIndexRoute
  '/expediente/': typeof ExpedienteIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin-mizu/notificacoes/atualizacoes': typeof AdminMizuNotificacoesAtualizacoesRoute
  '/admin-mizu/restaurantes/$id': typeof AdminMizuRestaurantesIdRoute
  '/admin-mizu/notificacoes/': typeof AdminMizuNotificacoesIndexRoute
  '/admin-mizu/restaurantes/': typeof AdminMizuRestaurantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/agenda'
    | '/auth'
    | '/avaliacoes'
    | '/customers'
    | '/dashboard'
    | '/demonstracao'
    | '/kds'
    | '/menu-admin'
    | '/orders'
    | '/perfil'
    | '/tables'
    | '/admin-mizu/assinaturas'
    | '/admin-mizu/configuracoes'
    | '/admin-mizu/cupons'
    | '/admin-mizu/logs'
    | '/admin-mizu/observacoes-excluidas'
    | '/admin-mizu/pagamentos'
    | '/admin-mizu/planos'
    | '/admin-mizu/suporte'
    | '/admin-mizu/usuarios'
    | '/dev/sheet-harness'
    | '/expediente/historico'
    | '/m/$slug'
    | '/pedido/$token'
    | '/q/$code'
    | '/r/$slug'
    | '/reset-password/success'
    | '/settings/notifications'
    | '/admin-mizu/'
    | '/expediente/'
    | '/reset-password/'
    | '/settings/'
    | '/admin-mizu/notificacoes/atualizacoes'
    | '/admin-mizu/restaurantes/$id'
    | '/admin-mizu/notificacoes/'
    | '/admin-mizu/restaurantes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/agenda'
    | '/auth'
    | '/avaliacoes'
    | '/customers'
    | '/dashboard'
    | '/demonstracao'
    | '/kds'
    | '/menu-admin'
    | '/orders'
    | '/perfil'
    | '/tables'
    | '/admin-mizu/assinaturas'
    | '/admin-mizu/configuracoes'
    | '/admin-mizu/cupons'
    | '/admin-mizu/logs'
    | '/admin-mizu/observacoes-excluidas'
    | '/admin-mizu/pagamentos'
    | '/admin-mizu/planos'
    | '/admin-mizu/suporte'
    | '/admin-mizu/usuarios'
    | '/dev/sheet-harness'
    | '/expediente/historico'
    | '/m/$slug'
    | '/pedido/$token'
    | '/q/$code'
    | '/r/$slug'
    | '/reset-password/success'
    | '/settings/notifications'
    | '/admin-mizu'
    | '/expediente'
    | '/reset-password'
    | '/settings'
    | '/admin-mizu/notificacoes/atualizacoes'
    | '/admin-mizu/restaurantes/$id'
    | '/admin-mizu/notificacoes'
    | '/admin-mizu/restaurantes'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/agenda'
    | '/auth'
    | '/avaliacoes'
    | '/customers'
    | '/dashboard'
    | '/demonstracao'
    | '/kds'
    | '/menu-admin'
    | '/orders'
    | '/perfil'
    | '/tables'
    | '/admin-mizu/assinaturas'
    | '/admin-mizu/configuracoes'
    | '/admin-mizu/cupons'
    | '/admin-mizu/logs'
    | '/admin-mizu/observacoes-excluidas'
    | '/admin-mizu/pagamentos'
    | '/admin-mizu/planos'
    | '/admin-mizu/suporte'
    | '/admin-mizu/usuarios'
    | '/dev/sheet-harness'
    | '/expediente/historico'
    | '/m/$slug'
    | '/pedido/$token'
    | '/q/$code'
    | '/r/$slug'
    | '/reset-password/success'
    | '/settings/notifications'
    | '/admin-mizu/'
    | '/expediente/'
    | '/reset-password/'
    | '/settings/'
    | '/admin-mizu/notificacoes/atualizacoes'
    | '/admin-mizu/restaurantes/$id'
    | '/admin-mizu/notificacoes/'
    | '/admin-mizu/restaurantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DemonstracaoRoute: typeof DemonstracaoRoute
  KdsRoute: typeof KdsRoute
  MenuAdminRoute: typeof MenuAdminRoute
  OrdersRoute: typeof OrdersRoute
  PerfilRoute: typeof PerfilRoute
  TablesRoute: typeof TablesRoute
  AdminMizuAssinaturasRoute: typeof AdminMizuAssinaturasRoute
  AdminMizuConfiguracoesRoute: typeof AdminMizuConfiguracoesRoute
  AdminMizuCuponsRoute: typeof AdminMizuCuponsRoute
  AdminMizuLogsRoute: typeof AdminMizuLogsRoute
  AdminMizuObservacoesExcluidasRoute: typeof AdminMizuObservacoesExcluidasRoute
  AdminMizuPagamentosRoute: typeof AdminMizuPagamentosRoute
  AdminMizuPlanosRoute: typeof AdminMizuPlanosRoute
  AdminMizuSuporteRoute: typeof AdminMizuSuporteRoute
  AdminMizuUsuariosRoute: typeof AdminMizuUsuariosRoute
  DevSheetHarnessRoute: typeof DevSheetHarnessRoute
  ExpedienteHistoricoRoute: typeof ExpedienteHistoricoRoute
  MSlugRoute: typeof MSlugRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
  QCodeRoute: typeof QCodeRoute
  RSlugRoute: typeof RSlugRoute
  ResetPasswordSuccessRoute: typeof ResetPasswordSuccessRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  AdminMizuIndexRoute: typeof AdminMizuIndexRoute
  ExpedienteIndexRoute: typeof ExpedienteIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AdminMizuNotificacoesAtualizacoesRoute: typeof AdminMizuNotificacoesAtualizacoesRoute
  AdminMizuRestaurantesIdRoute: typeof AdminMizuRestaurantesIdRoute
  AdminMizuNotificacoesIndexRoute: typeof AdminMizuNotificacoesIndexRoute
  AdminMizuRestaurantesIndexRoute: typeof AdminMizuRestaurantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kds': {
      id: '/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-admin': {
      id: '/menu-admin'
      path: '/menu-admin'
      fullPath: '/menu-admin'
      preLoaderRoute: typeof MenuAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/': {
      id: '/admin-mizu/'
      path: '/admin-mizu'
      fullPath: '/admin-mizu/'
      preLoaderRoute: typeof AdminMizuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/assinaturas': {
      id: '/admin-mizu/assinaturas'
      path: '/admin-mizu/assinaturas'
      fullPath: '/admin-mizu/assinaturas'
      preLoaderRoute: typeof AdminMizuAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/configuracoes': {
      id: '/admin-mizu/configuracoes'
      path: '/admin-mizu/configuracoes'
      fullPath: '/admin-mizu/configuracoes'
      preLoaderRoute: typeof AdminMizuConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/cupons': {
      id: '/admin-mizu/cupons'
      path: '/admin-mizu/cupons'
      fullPath: '/admin-mizu/cupons'
      preLoaderRoute: typeof AdminMizuCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/logs': {
      id: '/admin-mizu/logs'
      path: '/admin-mizu/logs'
      fullPath: '/admin-mizu/logs'
      preLoaderRoute: typeof AdminMizuLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/observacoes-excluidas': {
      id: '/admin-mizu/observacoes-excluidas'
      path: '/admin-mizu/observacoes-excluidas'
      fullPath: '/admin-mizu/observacoes-excluidas'
      preLoaderRoute: typeof AdminMizuObservacoesExcluidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/pagamentos': {
      id: '/admin-mizu/pagamentos'
      path: '/admin-mizu/pagamentos'
      fullPath: '/admin-mizu/pagamentos'
      preLoaderRoute: typeof AdminMizuPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/planos': {
      id: '/admin-mizu/planos'
      path: '/admin-mizu/planos'
      fullPath: '/admin-mizu/planos'
      preLoaderRoute: typeof AdminMizuPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/suporte': {
      id: '/admin-mizu/suporte'
      path: '/admin-mizu/suporte'
      fullPath: '/admin-mizu/suporte'
      preLoaderRoute: typeof AdminMizuSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/usuarios': {
      id: '/admin-mizu/usuarios'
      path: '/admin-mizu/usuarios'
      fullPath: '/admin-mizu/usuarios'
      preLoaderRoute: typeof AdminMizuUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/sheet-harness': {
      id: '/dev/sheet-harness'
      path: '/dev/sheet-harness'
      fullPath: '/dev/sheet-harness'
      preLoaderRoute: typeof DevSheetHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediente/': {
      id: '/expediente/'
      path: '/expediente'
      fullPath: '/expediente/'
      preLoaderRoute: typeof ExpedienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediente/historico': {
      id: '/expediente/historico'
      path: '/expediente/historico'
      fullPath: '/expediente/historico'
      preLoaderRoute: typeof ExpedienteHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/success': {
      id: '/reset-password/success'
      path: '/reset-password/success'
      fullPath: '/reset-password/success'
      preLoaderRoute: typeof ResetPasswordSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/notificacoes/': {
      id: '/admin-mizu/notificacoes/'
      path: '/admin-mizu/notificacoes'
      fullPath: '/admin-mizu/notificacoes/'
      preLoaderRoute: typeof AdminMizuNotificacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/notificacoes/atualizacoes': {
      id: '/admin-mizu/notificacoes/atualizacoes'
      path: '/admin-mizu/notificacoes/atualizacoes'
      fullPath: '/admin-mizu/notificacoes/atualizacoes'
      preLoaderRoute: typeof AdminMizuNotificacoesAtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/restaurantes/': {
      id: '/admin-mizu/restaurantes/'
      path: '/admin-mizu/restaurantes'
      fullPath: '/admin-mizu/restaurantes/'
      preLoaderRoute: typeof AdminMizuRestaurantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mizu/restaurantes/$id': {
      id: '/admin-mizu/restaurantes/$id'
      path: '/admin-mizu/restaurantes/$id'
      fullPath: '/admin-mizu/restaurantes/$id'
      preLoaderRoute: typeof AdminMizuRestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DemonstracaoRoute: DemonstracaoRoute,
  KdsRoute: KdsRoute,
  MenuAdminRoute: MenuAdminRoute,
  OrdersRoute: OrdersRoute,
  PerfilRoute: PerfilRoute,
  TablesRoute: TablesRoute,
  AdminMizuAssinaturasRoute: AdminMizuAssinaturasRoute,
  AdminMizuConfiguracoesRoute: AdminMizuConfiguracoesRoute,
  AdminMizuCuponsRoute: AdminMizuCuponsRoute,
  AdminMizuLogsRoute: AdminMizuLogsRoute,
  AdminMizuObservacoesExcluidasRoute: AdminMizuObservacoesExcluidasRoute,
  AdminMizuPagamentosRoute: AdminMizuPagamentosRoute,
  AdminMizuPlanosRoute: AdminMizuPlanosRoute,
  AdminMizuSuporteRoute: AdminMizuSuporteRoute,
  AdminMizuUsuariosRoute: AdminMizuUsuariosRoute,
  DevSheetHarnessRoute: DevSheetHarnessRoute,
  ExpedienteHistoricoRoute: ExpedienteHistoricoRoute,
  MSlugRoute: MSlugRoute,
  PedidoTokenRoute: PedidoTokenRoute,
  QCodeRoute: QCodeRoute,
  RSlugRoute: RSlugRoute,
  ResetPasswordSuccessRoute: ResetPasswordSuccessRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  AdminMizuIndexRoute: AdminMizuIndexRoute,
  ExpedienteIndexRoute: ExpedienteIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AdminMizuNotificacoesAtualizacoesRoute:
    AdminMizuNotificacoesAtualizacoesRoute,
  AdminMizuRestaurantesIdRoute: AdminMizuRestaurantesIdRoute,
  AdminMizuNotificacoesIndexRoute: AdminMizuNotificacoesIndexRoute,
  AdminMizuRestaurantesIndexRoute: AdminMizuRestaurantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
